import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Toodo App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`$inter.className bg-red `}>
        <header className="bg-red-700 px-5 py-5 flex gap-5 font-normal text-green-400">
        < Link href="/">Home</ Link>
        
        </header>
        {children}
        <footer className="bg-red-500 flex justify-center py-5">
          <p>&copy; 2023 - All rights reserved.</p>
        </footer>
        `
        </body>
    </html>
  )
}